# vim:ft=kitty
#
# name: Neon Ocean
#

# ------------------------
# Basic colours
# ------------------------

foreground              #D7F3FF
background              #08131D

selection_foreground    #08131D
selection_background    #19C9F3

# ------------------------
# Cursor
# ------------------------

cursor                  #42D6FF
cursor_text_color       #08131D

# ------------------------
# URLs
# ------------------------

url_color               #42D6FF

# ------------------------
# Borders
# ------------------------

active_border_color     #19C9F3
inactive_border_color   #163041
bell_border_color       #1CE8D9

# ------------------------
# Window titlebars
# ------------------------

wayland_titlebar_color system
macos_titlebar_color system

# ------------------------
# Tab bar
# ------------------------

active_tab_foreground   #08131D
active_tab_background   #19C9F3

inactive_tab_foreground #8FB4C7
inactive_tab_background #10222F

tab_bar_background      #061018

# ------------------------
# Marks
# ------------------------

mark1_foreground #08131D
mark1_background #42D6FF

mark2_foreground #08131D
mark2_background #1CE8D9

mark3_foreground #08131D
mark3_background #3CCEFF

# ------------------------
# Terminal colours
# ------------------------

# black
color0  #10222F
color8  #21465E

# red
color1  #FF6E7D
color9  #FF91A0

# green
color2  #28DFA5
color10 #45F5B8

# yellow
color3  #FFD76E
color11 #FFE89C

# blue
color4  #19C9F3
color12 #42D6FF

# magenta
color5  #4D7DFF
color13 #78A5FF

# cyan
color6  #1CE8D9
color14 #63FFF1

# white
color7  #C5E8F5
color15 #F3FDFF